services:

  intershop-keycloak:
    container_name: intershop-keycloak
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - backend

  payment-database:
    image: postgres:17.4
    container_name: payment-postgres
    ports:
      - "7541:5432"
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  payment-service:
    build: payservice/server
    image: payment
    container_name: payment
    ports:
      - "8081:8081"
    depends_on:
      payment-database:
        condition: service_healthy
      intershop-keycloak:
        condition: service_started
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://payment-database:5432/paymentdb
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=12345
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://intershop-keycloak:8080/realms/master
    networks:
      - backend

  intershop-database:
    image: postgres:17.4
    container_name: intershop-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=intershopdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  intershop-cache:
    image: redis:8.0.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "12345", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - backend

  intershop-service:
    build: shop/
    image: intershop
    container_name: intershop
    ports:
      - "8082:8082"
    depends_on:
      intershop-database:
        condition: service_healthy
      intershop-cache:
        condition: service_healthy
      payment-service:
        condition: service_started
      intershop-keycloak:
        condition: service_healthy
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://intershop-database:5432/intershopdb
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=12345
      - SPRING_DATA_REDIS_HOST=intershop-cache
      - SPRING_DATA_REDIS_PORT=6379
      - PAYMENT_SERVER_URL=http://payment-service:8081
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://intershop-keycloak:8080/realms/master
    networks:
      - backend

networks:
  backend: